#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
# default: gruvbox 
    colorscheme = "material"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    filemanager = 'nerdtree'
    bootstrap_before = "mysettings#before"
    bootstrap_after = "mysettings#after"
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "tools"

[[layers]]
name = "colorscheme"

[[layers]]
name = "checkers"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#WebAssembly"

[[layers]]
name = 'lang#r'

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#graphql"

[[layers]]
  name = "debug"

[[layers]]
name = "fzf"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#rust"

[[layers]]
name = "ctrlp"

[[layers]]
name = "github"

[[layers]]
name = "git"


[[layers]]
name = "lang#markdown"

[[layers]]
name = "shell"

[[layers]]
name = "sudo"

[[layers]]
name = "lsp"

[[layers]]
name = "lang#html"

[[layers]]
name = "tools"

[[layers]]
name = "VersionControl"

[[layers]]
name = "unite"

# ==========================
# Custom plugin installation
# ==========================

[[custom_plugins]]
name = "ryanoasis/vim-devicons"

[[custom_plugins]]
name = "airblade/vim-gitgutter"

[[custom_plugins]]
name =  "itchyny/vim-cursorword"

[[custom_plugins]]
name = "tpope/vim-obsession"

[[custom_plugins]]
name = "styled-components/vim-styled-components"

[[custom_plugins]]
name = "w0rp/ale"

# [[custom_plugins]]
# name = "jparise/vim-graphql"

[[custom_plugins]]
name = "peitalin/vim-jsx-typescript"

[[custom_plugins]]
name = "samuelsimoes/vim-jsx-utils"

[[custom_plugins]]
name = "tpope/vim-fugitive"

[[custom_plugins]]
name = "Ron89/thesaurus_query.vim"
# [[custom_plugins]]
# name = "beloglazov/vim-online-thesaurus"

[[custom_plugins]]
name = "heavenshell/vim-jsdoc"

[[custom_plugins]]
name = "artnez/vim-wipeout"

[[custom_plugins]]
name = "djoshea/vim-autoread"

[[custom_plugins]]
name  = "octref/RootIgnore"

[[custom_plugins]]
name = "wincent/command-t"

[[custom_plugins]]
name = "tpope/vim-liquid"

# [[custom_plugins]]
# name = "python-mode/python-mode"

# [[custom_plugins]]
# name = "python-rope/ropevim"

# [[custom_plugins]]
# name = "vim-vdebug/vdebug"

# [[custom_plugins]]
# name = "davidhalter/jedi-vim"

[[custom_plugins]]
name = "plytophogy/vim-virtualenv"

[[custom_plugins]]
name = "ludovicchabant/vim-gutentags"

[[cust_plugins]]
name = "liuchengxu/space-vim-dark"

[[custom_plugins]]
name = "vim-python/python-syntax"

# [[custom_plugins]]
# name = "raghur/vim-ghost"

[[custom_plugins]]
name = "iamcco/markdown-preview.nvim"

[[custom_plugins]]
name = "vim-pandoc/vim-pandoc"

[[custom_plugins]]
name = "vim-pandoc/vim-pandoc-syntax"

[[custom_plugins]]
name = "itchyny/dictionary.vim"
