#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # default: gruvbox 
    # others good ones: ["material"]
    colorscheme = "miramare"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = false
    filemanager = 'nerdtree'
    bootstrap_before = "mysettings#before"
    bootstrap_after = "mysettings#after"
    enable_neomake = false
    enable_ale = true
    lint_on_the_fly = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_method = "coc"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "tools"

[[layers]]
name = "colorscheme"

[[layers]]
name = "checkers"

[[layers]]
name = 'shell'
default_position = 'float'
default_height = 30

[[layers]]
name = "lang#WebAssembly"

[[layers]]
name = "lang#latex"
# install proselint

[[layers]]
name = 'lang#r'

[[layers]]
name = "lang#python"
enable_typeinfo = true
python_file_head = [
  '#!/usr/local/opt/python@3.8/bin/python3',
  '# -*- coding: utf-8 -*-',
  '',
  ''
]

[[layers]]
name = "core#statusline"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#ruby"

[[layers]]
name = "lang#scala"

[[layers]]
name = "lang#lua"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#graphql"

[[layers]]
name = "debug"

[[layers]]
name = "fzf"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "ctrlp"

[[layers]]
name = "lang#csharp"

[[layers]]
name = "github"

[[layers]]
name = "git"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "sudo"

# I am removing this because there might be some similarities between this and the autocomplete layer
# [[layers]]
# name = "lsp"

[[layers]]
name = "lang#html"

[[layers]]
name = "VersionControl"

# ==========================
# Custom plugin installation
# ==========================

[[custom_plugins]]
name = "airblade/vim-gitgutter"

[[custom_plugins]]
name =  "itchyny/vim-cursorword"

[[custom_plugins]]
name = "tpope/vim-obsession"

[[custom_plugins]]
name = "styled-components/vim-styled-components"

[[custom_plugins]]
name = "w0rp/ale"

# TYPESCRIPT
[[custom_plugins]]
name = "peitalin/vim-jsx-typescript"

[[custom_plugins]]
name = "leafgarland/typescript-vim"

# ======

[[custom_plugins]]
name = "samuelsimoes/vim-jsx-utils"

[[custom_plugins]]
name = "tpope/vim-fugitive"

[[custom_plugins]]
name = "Ron89/thesaurus_query.vim"

[[custom_plugins]]
name = "heavenshell/vim-jsdoc"

[[custom_plugins]]
name = "othree/jsdoc-syntax.vim"

[[custom_plugins]]
name = "styled-components/vim-styled-components"

[[custom_plugins]]
name = "artnez/vim-wipeout"

[[custom_plugins]]
name = "djoshea/vim-autoread"

[[custom_plugins]]
name = "tpope/vim-liquid"

[[custom_plugins]]
name = "plytophogy/vim-virtualenv"

[[custom_plugins]]
name = "iamcco/markdown-preview.nvim"

[[custom_plugins]]
name = "vim-pandoc/vim-pandoc"

[[custom_plugins]]
name = "vim-pandoc/vim-pandoc-syntax"

[[custom_plugins]]
name = "dhruvasagar/vim-table-mode"
# <Leader>tm

[[custom_plugins]]
name = "itchyny/dictionary.vim"

# Python3 syntax highlighting
[[custom_plugins]]
name = "numirias/semshi"

[[custom_plugins]]
name = "liuchengxu/vim-clap"

[[custom_plugins]]
name = "rhysd/git-messenger.vim"
# <Leader>gm

[[custom_plugins]]
name = "yuki-ycino/fzf-preview.vim"

[[custom_plugins]]
name = "liuchengxu/vista.vim"

# =======================================
# Color schemes / Themes / Visual stuff
# =======================================

# Only when Neovim 0.5.0+ gets here :P
# [[custom_plugins]]
# name = "wbthomason/packer.nvim"
# name = "windwp/nvim-autopairs"
# name = "glepnir/galaxyline.nvim"
# name = "akinsho/nvim-bufferline.lua"
# name = "kyazdani42/nvim-web-devicons"
# name = "nvim-telescope/telescope.nvim"
# name = "lewis6991/gitsigns.nvim"
# name = "nvim-compe"
# name = "neovim/nvim-lspconfig"
# name = "kyazdani42/nvim-tree.lua"
# name = "folke/lsp-trouble.nvim"
# name = "folke/tokyonight.nvim"
# name = "hill2/floating.nvim"
# name = "ray-x/navigator.lua"
# name = "kdav5758/TrueZen.nvim"

[[custom_plugins]]
name = "flazz/vim-colorschemes"

[[custom_plugins]]
name = "franbach/miramare"

[[custom_plugins]]
name = "skbolton/embark"

[[custom_plugins]]
name = "joshdick/onedark.vim"

[[custom_plugins]]
name = "mhartington/oceanic-next"

[[custom_plugins]]
name = "liuchengxu/space-vim-dark"

# ==========================
# Iconography / Symbols
# ==========================

[[custom_plugins]]
name = "onsails/lspkind-nvim"
# Must have declarations in config files

[[custom_plugins]]
name = "junegunn/vim-emoji"

[[custom_plugins]]
name = "rizzatti/dash.vim"

[[custom_plugins]]
name = "ryanoasis/vim-webdevicons"


# ==========================

# [[custom_plugins]]
# name = "ripxorip/aerojump.nvim"

[[custom_plugins]]
name = "APZelos/blamer.nvim"

[[custom_plugins]]
name = "adamclerk/vim-razor"

[[custom_plugins]]
name = "OrangeT/vim-csharp"

[[custom_plugins]]
name = "tpope/vim-rails"
